name: 'kook_dbt'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]

models:
  kook_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
