WITH orders AS (
    SELECT * FROM {{ ref('stg_orders') }}
),

order_agg AS (
    SELECT
        order_id,
        MIN(created_at) AS created_at,
        MIN(paid_at) AS paid_at,
        MIN(fulfilled_at) AS fulfilled_at,
        MIN(cancelled_at) AS cancelled_at,
        MIN(order_name) AS order_name,
        MIN(customer_email) AS customer_email,
        MIN(customer_name) AS customer_name,
        MIN(financial_status) AS financial_status,
        MIN(fulfillment_status) AS fulfillment_status,
        MIN(currency) AS currency,
        MIN(total_amount) AS total_amount,
        MIN(subtotal) AS subtotal,
        MIN(shipping_amount) AS shipping_amount,
        MIN(tax_amount) AS tax_amount,
        MIN(discount_amount) AS discount_amount,
        MIN(refunded_amount) AS refunded_amount,
        MIN(discount_code) AS discount_code,
        MIN(sales_channel) AS sales_channel,
        MIN(payment_method) AS payment_method,
        MIN(shipping_method) AS shipping_method,
        MIN(risk_level) AS risk_level,
        MIN(billing_city) AS billing_city,
        MIN(billing_state) AS billing_state,
        MIN(billing_state_name) AS billing_state_name,
        MIN(billing_country) AS billing_country,
        MIN(billing_zip) AS billing_zip,
        MIN(order_tags) AS order_tags,
        COUNT(*) AS line_item_count,
        SUM(line_item_quantity) AS total_units
    FROM orders
    GROUP BY order_id
)

SELECT
    order_id,
    created_at,
    paid_at,
    fulfilled_at,
    cancelled_at,
    order_name,
    customer_email,
    customer_name,
    financial_status,
    fulfillment_status,
    currency,
    total_amount,
    subtotal,
    shipping_amount,
    tax_amount,
    discount_amount,
    refunded_amount,
    ROUND(total_amount - COALESCE(refunded_amount, 0), 2) AS net_revenue,
    discount_code,
    CASE WHEN discount_code IS NOT NULL AND discount_code != '' THEN TRUE ELSE FALSE END AS has_discount,
    CASE WHEN refunded_amount > 0 THEN TRUE ELSE FALSE END AS is_refunded,
    CASE WHEN cancelled_at IS NOT NULL THEN TRUE ELSE FALSE END AS is_cancelled,
    sales_channel,
    payment_method,
    shipping_method,
    risk_level,
    billing_city,
    billing_state,
    billing_state_name,
    billing_country,
    billing_zip,
    order_tags,
    line_item_count,
    total_units,
    DATE_TRUNC('MONTH', created_at) AS order_month,
    DATE_TRUNC('WEEK', created_at) AS order_week,
    DAYOFWEEK(created_at) AS day_of_week
FROM order_agg
